name: docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # runs daily at 00:00

  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - run: rm -rf .git # prevent build errors since buildvcs=true if there's a .git dir
      - uses: int128/kaniko-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          target: scanservjs-brscan4
          tags: |
            scanservjs-brscan4:release-${{ steps.get_version.outputs.VERSION }}
            scanservjs-brscan4:${{ steps.get_version.outputs.VERSION }}
            scanservjs-brscan4:latest
          #tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
