name: docker

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'LICENSE'
      - '**/*.md'
      - 'Dockerfile'
      - 'entrypoint.sh'
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      - run: rm -rf .git # prevent build errors since buildvcs=true if there's a .git dir
      - uses: int128/kaniko-action@v1
        with:
          push: true
          target: scanservjs-brscan4
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
